/*
  cjshopt_registry.cpp

  This file is part of cjsh, CJ's Shell

  MIT License

  Copyright (c) 2026 Caden Finley

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*/

#include "cjshopt_registry.h"

#include <string>
#include <string_view>
#include <vector>

#include "agent_mode.h"
#include "cjshopt_command.h"

namespace {
std::vector<CjshoptCompletionValue> toggle_values(const char* on, const char* off) {
    return {{"on", on}, {"off", off}, {"status", "Show current setting"}};
}
}  // namespace

const std::vector<CjshoptSubcommandDescriptor>& cjshopt_subcommands() {
    static const std::vector<CjshoptSubcommandDescriptor> commands = {
        {"style_def",
         style_def_command,
         "Appearance:",
         27,
         {{"<token_type> <style>", {"Define or redefine a syntax highlighting style."}},
          {"preview|--reset", {"Preview current styles or reset defaults."}}},
         "Define syntax highlight styles",
         "Define or reset syntax styles",
         {{"preview", "Show current syntax style preview"},
          {"--reset", "Reset all highlight styles to defaults", true}}},
        {"completion-case",
         completion_case_command,
         "Completion and hints:",
         3,
         {{"<on|off|status>", {"Match completions case-sensitively (default: off)."}}},
         "Configure completion case sensitivity",
         "",
         toggle_values("Enable case-sensitive matches", "Disable case sensitivity")},
        {"history-search-case",
         history_search_case_command,
         "History:",
         13,
         {{"<on|off|status>", {"Match fuzzy history searches case-sensitively (default: on)."}}},
         "Configure fuzzy history case sensitivity",
         "",
         toggle_values("Require exact case in fuzzy history", "Match history regardless of case")},
        {"history-directory",
         history_directory_command,
         "History:",
         10,
         {{"<on|off|status>",
           {"Scope interactive history to the current directory (default: off)."}}},
         "Scope history to the current directory",
         "",
         toggle_values("Scope history to the current directory",
                       "Recall history from all directories")},
        {"history-directory-subdirs",
         history_directory_subdirs_command,
         "History:",
         11,
         {{"<on|off|status>",
           {"Include nested directories when directory scope is on (default: off)."}}},
         "Include nested directories in history",
         "",
         toggle_values("Include commands from nested directories",
                       "Exclude commands from nested directories")},
        {"history-directory-parents",
         history_directory_parents_command,
         "History:",
         12,
         {{"<on|off|status>",
           {"Include all ancestor directories when scope is on (default: off)."}}},
         "Include ancestor directories in history",
         "",
         toggle_values("Include commands from all ancestor directories up to /",
                       "Exclude commands from ancestor directories")},
        {"completion-spell",
         completion_spell_command,
         "Completion and hints:",
         4,
         {{"<on|off|status>", {"Suggest spelling corrections in completions (default: on)."}}},
         "Configure completion spell correction",
         "",
         toggle_values("Enable spell correction", "Disable spell correction")},
        {"completion-spell-enter",
         completion_spell_enter_command,
         "Completion and hints:",
         5,
         {{"<on|off|status>", {"Apply a single spelling correction on Enter (default: off)."}}},
         "Auto-apply a single spell correction when pressing Enter",
         "",
         toggle_values("Auto-apply a single spell correction on Enter",
                       "Submit input without Enter autocorrection")},
        {"completion-learning",
         completion_learning_command,
         "Completion and hints:",
         6,
         {{"<on|off|status>", {"Learn completions automatically from man pages (default: on)."}}},
         "Toggle completion learning",
         "Toggle completion learning",
         toggle_values("Allow on-demand completion scraping", "Only use cached completions")},
        {"exit-confirmation",
         exit_confirmation_command,
         "Shell behavior and agent mode:",
         47,
         {{"<smart|always|never|status>",
           {"Control when exit requires confirmation (default: smart)."}}},
         "Control when exit requires confirmation",
         "Control exit confirmation",
         {{"smart", "Confirm only when running or stopped jobs exist"},
          {"always", "Confirm every exit request"},
          {"never", "Never confirm exit requests"},
          {"status", "Show current mode"}}},
        {"smart-cd",
         smart_cd_command,
         "Shell behavior and agent mode:",
         44,
         {{"<on|off|status>", {"Enable smart cd auto-jumps (default: on)."}}},
         "Toggle smart cd auto-jumps",
         "",
         toggle_values("Enable smart cd auto-jumps", "Disable smart cd auto-jumps")},
        {"dialect",
         dialect_command,
         "Shell behavior and agent mode:",
         45,
         {{"<cjsh|posix|status>",
           {"Select the language dialect for subsequent commands.",
            "Configure language options with shopt (for example, shopt -s extglob)."}}},
         "Select cjsh or posix semantics",
         "Select the shell language dialect",
         {{"cjsh", "Use native cjsh semantics"},
          {"posix", "Use strict POSIX semantics"},
          {"status", "Print the selected dialect"}}},
        {"script-extension-interpreter",
         script_extension_interpreter_command,
         "Shell behavior and agent mode:",
         46,
         {{"<on|off|status>", {"Infer script runners from file extensions (default: on)."}}},
         "Toggle extension-based script runners",
         "",
         toggle_values("Enable extension-based script runners",
                       "Disable extension-based script runners")},
        {"line-numbers",
         line_numbers_command,
         "Appearance:",
         28,
         {{"<on|off|relative|absolute|status>",
           {"Show line numbers in multiline input (default: on, absolute)."}}},
         "Configure multiline line numbers",
         "",
         {{"on", "Enable absolute line numbers"},
          {"off", "Hide line numbers"},
          {"relative", "Show relative line numbers"},
          {"absolute", "Show absolute line numbers"},
          {"status", "Show current setting"}}},
        {"scrollbars",
         scrollbars_command,
         "Appearance:",
         33,
         {{"<on|off|status>", {"Show or hide input and menu scrollbars (default: on)."}}},
         "Toggle input and menu scrollbars",
         "",
         toggle_values("Show input and menu scrollbars", "Hide input and menu scrollbars")},
        {"line-numbers-continuation",
         line_numbers_continuation_command,
         "Appearance:",
         29,
         {{"<on|off|status>", {"Keep line numbers when a continuation prompt is active."}}},
         "Control line numbers during continuation prompts",
         "",
         toggle_values("Show line numbers with continuation prompts",
                       "Hide line numbers when a continuation prompt is active")},
        {"line-numbers-replace-prompt",
         line_numbers_replace_prompt_command,
         "Appearance:",
         30,
         {{"<on|off|status>", {"Replace the final prompt line with line numbers (default: off)."}}},
         "Replace the final prompt line with line numbers",
         "",
         toggle_values("Replace the final prompt line with line numbers",
                       "Keep the final prompt line visible")},
        {"current-line-number-highlight",
         current_line_number_highlight_command,
         "Appearance:",
         31,
         {{"<on|off|status>", {"Highlight the current line number (default: on)."}}},
         "Toggle current line number highlighting",
         "",
         toggle_values("Highlight the active line number", "Disable line number highlighting")},
        {"multiline-start-lines",
         multiline_start_lines_command,
         "Prompt and multiline input:",
         22,
         {{"<count|status>", {"Set the initial multiline prompt height (default: 1)."}}},
         "Set default multiline prompt height",
         "",
         {{"status", "Show current multiline height"}}},
        {"multiline-max-lines",
         multiline_max_lines_command,
         "Prompt and multiline input:",
         23,
         {{"<count|status>", {"Limit visible multiline input rows (default: 15)."}}},
         "Limit visible multiline input rows",
         "",
         {{"status", "Show the multiline viewport limit"}}},
        {"completion-menu-max-lines",
         completion_menu_max_lines_command,
         "Menus:",
         15,
         {{"<count|status>", {"Limit completion menu content rows (default: 15)."}}},
         "Limit completion menu content rows",
         "Limit completion menu content rows",
         {{"status", "Show the completion menu height limit"}}},
        {"history-menu-max-lines",
         history_menu_max_lines_command,
         "Menus:",
         16,
         {{"<count|status>", {"Limit history menu content rows (default: 15)."}}},
         "Limit history menu content rows",
         "Limit history menu content rows",
         {{"status", "Show the history menu height limit"}}},
        {"command-palette-max-lines",
         command_palette_max_lines_command,
         "Menus:",
         17,
         {{"<count|status>", {"Limit command palette content rows (default: 15)."}}},
         "Limit command palette content rows",
         "Limit command palette content rows",
         {{"status", "Show the command palette height limit"}}},
        {"custom-menu-max-lines",
         custom_menu_max_lines_command,
         "Menus:",
         18,
         {{"<count|status>", {"Limit custom menu content rows (default: 15)."}}},
         "Limit custom menu content rows",
         "Limit custom menu content rows",
         {{"status", "Show the custom menu height limit"}}},
        {"multiline-bottom-lines",
         multiline_bottom_lines_command,
         "Prompt and multiline input:",
         24,
         {{"<count|status>", {"Set the input and menu scroll margin (default: 3)."}}},
         "Set the input and menu scroll margin",
         "",
         {{"status", "Show the cursor scroll margin"}}},
        {"hint-delay",
         hint_delay_command,
         "Completion and hints:",
         9,
         {{"<milliseconds|status>", {"Set or show the delay before inline hints appear."}}},
         "Adjust inline hint delay",
         "Adjust inline hint delay",
         {{"status", "Show the current delay in milliseconds"},
          {"--status", "Show the current delay in milliseconds", true}}},
        {"idle-timeout",
         idle_timeout_command,
         "Shell behavior and agent mode:",
         48,
         {{"<seconds|off|status>",
           {"Run inactivity hooks after the specified delay (default: off)."}}},
         "Configure the idle hook timeout",
         "Configure terminal inactivity hooks",
         {{"off", "Disable idle hooks"},
          {"status", "Show the current timeout"},
          {"--status", "Show the current timeout", true}}},
        {"completion-preview",
         completion_preview_command,
         "Completion and hints:",
         2,
         {{"<on|off|status>", {"Preview the selected completion (default: on)."}}},
         "Toggle completion preview",
         "",
         toggle_values("Enable completion preview", "Disable completion preview")},
        {"completion-auto-menu",
         completion_auto_menu_command,
         "Completion and hints:",
         0,
         {{"<on|off|status>",
           {"Show completions while typing. Tab activates the menu (default: off)."}}},
         "Show completions while typing. Tab activates",
         "",
         toggle_values("Show passive completions while typing. Tab activates",
                       "Open completions only on request (default)")},
        {"completion-click-accept",
         completion_click_accept_command,
         "Keyboard and mouse:",
         43,
         {{"<on|off|status>", {"Accept completion entries when clicked (default: off)."}}},
         "Control whether clicks accept completion entries",
         "",
         toggle_values("Always accept completion entries on click",
                       "Click selects entries without accepting")},
        {"menu-highlighting",
         menu_highlighting_command,
         "Menus:",
         19,
         {{"<none|single|all|reverse|status>",
           {"Syntax-highlight completion and history menu items (default: none)."}}},
         "Syntax-highlight completion and history menu items",
         "",
         {{"none", "Do not syntax-highlight menu items"},
          {"single", "Highlight only the selected menu item"},
          {"all", "Highlight every rendered menu item"},
          {"reverse", "Highlight every rendered menu item except the selected item"},
          {"status", "Show current mode"}}},
        {"visible-whitespace",
         visible_whitespace_command,
         "Appearance:",
         32,
         {{"<on|off|status>", {"Show whitespace characters in the editor (default: off)."}}},
         "Toggle visible whitespace",
         "",
         toggle_values("Show whitespace markers", "Hide whitespace markers")},
        {"line-wrap-marker",
         line_wrap_marker_command,
         "Appearance:",
         34,
         {{"<marker|status>", {"Set a single wrap character. Use '' to disable it."}}},
         "Set the character at wrapped line ends",
         "",
         {{"''", "Hide the symbol at wrapped line ends"}, {"status", "Show the current marker"}}},
        {"hint",
         hint_command,
         "Completion and hints:",
         8,
         {{"<on|off|status>", {"Show inline completion hints (default: on)."}}},
         "Toggle inline hints",
         "",
         toggle_values("Enable inline hints", "Disable inline hints")},
        {"multiline-indent",
         multiline_indent_command,
         "Prompt and multiline input:",
         21,
         {{"<on|off|status>", {"Automatically indent multiline input (default: on)."}}},
         "Toggle multiline auto-indent",
         "",
         toggle_values("Enable multiline auto-indent", "Disable multiline auto-indent")},
        {"multiline",
         multiline_command,
         "Prompt and multiline input:",
         20,
         {{"<on|off|status>", {"Enable multiline input (default: on)."}}},
         "Toggle multiline input",
         "",
         toggle_values("Enable multiline input", "Disable multiline input")},
        {"inline-help",
         inline_help_command,
         "Status and help:",
         39,
         {{"<on|off|status>", {"Show inline help messages (default: on)."}}},
         "Toggle inline help",
         "",
         toggle_values("Enable inline help", "Disable inline help")},
        {"status-hints",
         status_hints_command,
         "Status and help:",
         36,
         {{"<off|normal|transient|persistent|status>",
           {"Control the default status hint banner (default: normal)."}}},
         "Control status hint visibility",
         "",
         {{"off", "Never display the hint banner"},
          {"normal", "Only show when everything else is blank"},
          {"transient", "Show when the status line has no content"},
          {"persistent", "Always prepend hints above other lines"},
          {"status", "Show current mode"}}},
        {"status-line",
         status_line_command,
         "Status and help:",
         35,
         {{"<on|off|status>", {"Show the status area below the prompt (default: on)."}}},
         "Disable the status row entirely",
         "",
         toggle_values("Show the status row", "Hide the status row entirely")},
        {"status-reporting",
         status_reporting_command,
         "Status and help:",
         37,
         {{"<on|off|status>",
           {"Show command validation messages in the status area (default: on)."}}},
         "Mute cjsh status messages",
         "",
         toggle_values("Show cjsh validation output", "Hide cjsh validation output")},
        {"status-line-callback",
         status_line_callback_command,
         "Status and help:",
         38,
         {{"<function_name|off|status>",
           {"Run a shell function to supply custom status-line text."}}},
         "Run a shell function to publish status-line text",
         "",
         {{"off", "Disable custom status-line callback output"},
          {"status", "Show current callback setting"}}},
        {"mouse-clicking",
         mouse_clicking_command,
         "Keyboard and mouse:",
         41,
         {{"<all-off|off|simple|smart|status>",
           {"Configure mouse capture for prompts and menus (default: off)."}}},
         "Configure prompt and menu mouse capture",
         "",
         {{"all-off", "Never capture mouse events, including in menus"},
          {"off", "Capture only in expanded/interactive menus"},
          {"simple", "Enable mouse capture with manual toggles"},
          {"smart", "Enable auto suspend/resume mouse handling"},
          {"on", "Alias for simple mode"},
          {"disabled", "Alias for all-off mode"},
          {"status", "Show current setting"}}},
        {"mouse-clicking-status-line",
         mouse_clicking_status_line_command,
         "Keyboard and mouse:",
         42,
         {{"<on|off|status>", {"Show the mouse-clicking status indicator (default: on)."}}},
         "Toggle the mouse-clicking status indicator line",
         "",
         toggle_values("Show the mouse-clicking status indicator",
                       "Hide the mouse-clicking status indicator")},
        {"auto-tab",
         auto_tab_command,
         "Completion and hints:",
         1,
         {{"<on|off|status>", {"Automatically start tab completion (default: off)."}}},
         "Toggle automatic tab completion",
         "",
         toggle_values("Enable automatic tab completion", "Disable automatic tab completion")},
        {"prompt-newline",
         prompt_newline_command,
         "Prompt and multiline input:",
         25,
         {{"<on|off|status>", {"Add a newline after command execution (default: off)."}}},
         "Toggle newline after command execution",
         "",
         toggle_values("Insert a newline after every command", "Skip the post-command newline")},
        {"right-prompt-follow-cursor",
         right_prompt_follow_cursor_command,
         "Prompt and multiline input:",
         26,
         {{"<on|off|status>", {"Keep the inline right prompt on the cursor row (default: off)."}}},
         "Move the right prompt with the cursor",
         "",
         toggle_values("Move the right prompt with the cursor",
                       "Keep the right prompt pinned to the first row")},
        {"agent-mode",
         agent_mode::command,
         "Shell behavior and agent mode:",
         49,
         {{"<subcommand> [...]", {"Configure agent assistance."}}},
         "Configure agent assistance",
         "Configure agent assistance",
         {{"set", "Add or replace an agent executor"},
          {"list", "Show configured executors"},
          {"status", "Show agent-mode status"},
          {"on", "Enable agent assistance"},
          {"off", "Disable agent assistance"},
          {"key", "Configure the activation key"},
          {"clear", "Remove executor configuration"},
          {"reset", "Restore agent-mode defaults"}}},
        {"keybind",
         keybind_command,
         "Keyboard and mouse:",
         40,
         {{"<subcommand> [...]", {"Inspect or modify key bindings. Changes apply immediately."}}},
         "Inspect or modify key bindings",
         "Inspect or modify key bindings",
         {{"list", "Show current key bindings"},
          {"set", "Replace bindings for an action"},
          {"add", "Add bindings for an action"},
          {"clear", "Remove bindings for key sequences"},
          {"clear-action", "Remove bindings for an action"},
          {"reset", "Restore default key bindings"},
          {"profile", "Manage key binding profiles"},
          {"ext", "Manage command key bindings"}}},
        {"generate-profile",
         generate_profile_command,
         "Startup files:",
         51,
         {{"[-f|--force] [--alt]", {"Generate ~/.cjprofile."}}},
         "Generate ~/.cjprofile",
         "Generate ~/.cjprofile",
         {{"--force", "Overwrite the existing profile", true},
          {"-f", "Overwrite the existing profile", true},
          {"--alt", "Write to the alternate configuration path", true},
          {"--help", "Show usage information", true},
          {"-h", "Show usage information", true}}},
        {"generate-env",
         generate_env_command,
         "Startup files:",
         50,
         {{"[-f|--force] [--alt]", {"Generate ~/.cjshenv."}}},
         "Generate ~/.cjshenv",
         "Generate ~/.cjshenv",
         {{"--force", "Overwrite the existing env file", true},
          {"-f", "Overwrite the existing env file", true},
          {"--alt", "Write to the alternate configuration path", true},
          {"--help", "Show usage information", true},
          {"-h", "Show usage information", true}}},
        {"generate-rc",
         generate_rc_command,
         "Startup files:",
         52,
         {{"[-f|--force] [--alt]", {"Generate ~/.cjshrc."}}},
         "Generate ~/.cjshrc",
         "Generate ~/.cjshrc",
         {{"--force", "Overwrite the existing rc file", true},
          {"-f", "Overwrite the existing rc file", true},
          {"--alt", "Write to the alternate configuration path", true},
          {"--help", "Show usage information", true},
          {"-h", "Show usage information", true}}},
        {"generate-logout",
         generate_logout_command,
         "Startup files:",
         53,
         {{"[-f|--force] [--alt]", {"Generate ~/.cjlogout."}}},
         "Generate ~/.cjlogout",
         "Generate ~/.cjlogout",
         {{"--force", "Overwrite the existing logout file", true},
          {"-f", "Overwrite the existing logout file", true},
          {"--alt", "Write to the alternate configuration path", true},
          {"--help", "Show usage information", true},
          {"-h", "Show usage information", true}}},
        {"set-history-max",
         set_history_max_command,
         "History:",
         14,
         {{"<number|default|status>", {"Configure history persistence limits."}}},
         "Configure history persistence",
         "Configure history persistence",
         {{"default", "Restore the default history limit"},
          {"--default", "Restore the default history limit", true},
          {"status", "Display the current history limit"},
          {"--status", "Display the current history limit", true}}},
        {"set-completion-max",
         set_completion_max_command,
         "Completion and hints:",
         7,
         {{"<number|default|status>", {"Limit the number of completion suggestions."}}},
         "Limit completion suggestions",
         "Limit completion suggestions",
         {{"default", "Restore the default completion limit"},
          {"--default", "Restore the default completion limit", true},
          {"status", "Display the current completion limit"},
          {"--status", "Display the current completion limit", true}}},
    };
    return commands;
}

const CjshoptSubcommandDescriptor* find_cjshopt_subcommand(std::string_view name) {
    for (const auto& command : cjshopt_subcommands()) {
        if (name == command.name) {
            return &command;
        }
    }
    return nullptr;
}

std::string cjshopt_subcommand_usage(std::string_view name) {
    const auto* command = find_cjshopt_subcommand(name);
    if (command == nullptr) {
        return "Usage: " + std::string(name);
    }
    return "Usage: " + std::string(command->name) + " " + command->usage.front().arguments;
}
